Dockerfile-api, Taskfile.yml, example-commit, requirements-api.txt
Problem:
Versioned docker images have incorrectly specified build-args.
Solution:
Added VERSION= in build-args. Additionally upgraded pip and suppressed
annoying warning messages.
Signed-off-by: eccles <phewlett76@gmail.com>
=> Versioned images are built incorrectly.

requirements-api.txt
Problem:
Outdated version of cryptography library used in samples.
Solution:
Updated dependency list to currently recommended version.
Signed-off-by: JAG-UK <jon.geater@gmail.com>
=> Update cryptogrpahy dependencies to keep up with security patches

.gitignore, DEVELOPERS.md, README.md, archivist_samples/door_entry/main.py, archivist_samples/door_entry/run.py, archivist_samples/estate_info/main.py, archivist_samples/signed_records/main.py, archivist_samples/synsation/analyze.py, archivist_samples/synsation/charger.py, archivist_samples/synsation/ev_charger_device.py, archivist_samples/synsation/initialise.py, archivist_samples/synsation/jitsuinator.py, archivist_samples/synsation/maintenance_worker.py, archivist_samples/synsation/recall_worker.py, archivist_samples/synsation/synsation_corporation.py, archivist_samples/synsation/synsation_industries.py, archivist_samples/synsation/synsation_smartcity.py, archivist_samples/synsation/wanderer.py, archivist_samples/testing/__init__.py, archivist_samples/testing/accesscontrol.py, archivist_samples/testing/logger.py, archivist_samples/testing/time_warp.py, requirements.txt
Problem:
The root logger in the archivist dependency used a predefined settings.
Solution:
Upgrade to archivist0.2.0a1 and use default root logger settings with
helper module.
=> Remove root logger from archivist dependency

requirements.txt
Problem:
The pyyaml package is missing from dependency list.
Solution:
Add pyyaml to requirements.tx.
=> Missing yaml dependency

MANIFEST.in, archivist_samples/door_entry/images/__init__.py, archivist_samples/door_entry/images/assets/__init__.py, archivist_samples/door_entry/images/events/__init__.py, archivist_samples/door_entry/run.py, archivist_samples/synsation/ev_charger_device.py, archivist_samples/synsation/images/__init__.py, archivist_samples/synsation/images/assets/__init__.py, archivist_samples/synsation/initialise.py, archivist_samples/synsation/jitsuinator.py, archivist_samples/synsation/locations/__init__.py, archivist_samples/synsation/synsation_corporation.py, archivist_samples/synsation/synsation_industries.py, archivist_samples/synsation/synsation_manufacturing.py, archivist_samples/synsation/synsation_smartcity.py, archivist_samples/synsation/util.py, archivist_samples/synsation/wanderer.py, archivist_samples/testing/namespace.py, requirements.txt, setup.py
Problem:
The internal tests will not run without internal images and other files.
Solution:
Added data files to wheel package and used pkg_resources to read them in
the internal code.
=> Data files missing from wheel package.

archivist_samples/door_entry/run.py, archivist_samples/synsation/analyze.py, archivist_samples/synsation/ev_charger_device.py, archivist_samples/synsation/jitsuinator.py, archivist_samples/synsation/maintenance_worker.py, archivist_samples/synsation/recall_worker.py, archivist_samples/synsation/synsation_corporation.py, archivist_samples/synsation/synsation_industries.py, archivist_samples/synsation/synsation_manufacturing.py, archivist_samples/synsation/synsation_smartcity.py, archivist_samples/synsation/util.py, archivist_samples/synsation/wanderer.py, archivist_samples/testing/asset.py
Problem:
The make_event_json factory function serves no puprose except to make
reuse difficult.
Solution:
Replace with MyAsset class with methods that reflect user's expected
use cases such as 'update_firmware' etc....
Additionally make all events use Recordevidence' behaviour.
=> Make_event_json factory function unnecessary.

DEVELOPERS.md, README.md, archivist_samples/door_entry/main.py, archivist_samples/estate_info/main.py, archivist_samples/signed_records/main.py, archivist_samples/software_bill_of_materials/main.py, archivist_samples/software_bill_of_materials/run.py, archivist_samples/software_bill_of_materials/software_deployment.py, archivist_samples/software_bill_of_materials/software_package.py, archivist_samples/synsation/analyze.py, archivist_samples/synsation/charger.py, archivist_samples/synsation/initialise.py, archivist_samples/synsation/jitsuinator.py, archivist_samples/synsation/wanderer.py, archivist_samples/testing/namespace.py, archivist_samples/testing/parser.py, requirements.txt, scripts/api.sh, scripts/samples.sh
Problem:
New release of SAAS and python SDK supports storing evidence
on the ledger or tenant storage (a lower cost solution)
Solution:
Use 0.3.0a1 version of python SDK and specify LEDGER for SBOM
sample. Other code is left as-is (which will currently default to
LEDGER bu, at some later date) default to TENANT_STORAGE,
=> Use storage integrity for SBOM

DEVELOPERS.md, README.md, Taskfile.yml, archivist_samples/door_entry/main.py, archivist_samples/door_entry/run.py, archivist_samples/estate_info/main.py, archivist_samples/signed_records/main.py, archivist_samples/software_bill_of_materials/README.md, archivist_samples/software_bill_of_materials/main.py, archivist_samples/synsation/analyze.py, archivist_samples/synsation/charger.py, archivist_samples/synsation/initialise.py, archivist_samples/synsation/jitsuinator.py, archivist_samples/synsation/wanderer.py, archivist_samples/testing/parser.py, archivist_samples/wipp/main.py, archivist_samples/wipp/run.py, archivist_samples/wipp/wipp.py, requirements.txt, scripts/samples.sh
Problem:
Common code is moved to pythonSDK.
Solution:
Use latest pythonSDK 0.5.0 and remove unneeded code.
=> Latest features of pythonSDK

pyproject.toml, setup.py
Problem:
Tagging a release results in a version of 0.0.0.
Solution:
Pinned setuptools-git-versioning to v1.7.4 as later versions use
pyproject.tml and do not support python 3.6
=> Git versioning is broken

Taskfile.yml, requirements.txt, setup.cfg
Problem:
Entry points and package date was missing from wheel.
Solution:
Modified setup.cfg.
=> Fix missing package data in wheel

Taskfile.yml, scripts/api.sh
Problem:
The company name is changed from Jitsuin to RKVST.
Solution:
Only the name of the internal docker image is changed. All other jitsuin changes require upstream work that must be planned properly.
Signed-off-by: User Name <phewlett76@gmail.com>
=> Jitsuin still used.

archivist_samples/door_entry/run.py, archivist_samples/signed_records/main.py, archivist_samples/software_bill_of_materials/run.py, archivist_samples/software_bill_of_materials/software_deployment.py, archivist_samples/software_bill_of_materials/software_package.py, archivist_samples/synsation/simulator.py, archivist_samples/testing/archivist_parser.py, archivist_samples/wipp/run.py, archivist_samples/wipp/wipp.py, requirements-dev.txt, requirements.txt
Problem:
If an attachments upload encounters a 429 then the connection is closed resulting in a zero length file.
Solution:
Make sure that Verify is True which will enable keep-alive. Additionally upgrade all dependencies and reformat code to latest standard.
=> Attachments upload with 429

archivist_samples/door_entry/run.py, archivist_samples/software_bill_of_materials/run.py, archivist_samples/software_bill_of_materials/software_package.py, archivist_samples/synsation/simulator.py, archivist_samples/synsation/synsation_corporation.py, archivist_samples/synsation/synsation_manufacturing.py, archivist_samples/testing/assets.py, archivist_samples/wipp/run.py, archivist_samples/wipp/wipp.py
Attachment attribute naming needs fixing to correctly use arc_primary_images for the WIPP samples. More descriptive names should also be used for other attachment attributes where possible (this is a regression introduced by the recent switch to new style attachments.)
This PR:
- Fixes attribute naming and primary images for WIPP to resolve issue #56 
- Fixes naming of attributes in other samples
- Introduces a standard type for describing attachments
Does not make significant improvements to the software_deployment sample as its not used / deprecated
=> Fix attachment attribute naming

archivist_samples/signed_records/main.py, requirements.txt
Problem:
cryptography dependency has security vulnerabilities CVE-2023-0286 High severity
CVE-2023-23931 Moderate severity
Solution:
Upgrade cryptography to v41.0.
Fixes [AB#7856](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/7856)
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>
=> Dependabot alert for cryptography v38

requirements.txt
Problem:
Security vulnerability in dependency.
Solution:
Upgrade rkvst-archivist to v0.23.0.
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>
=> Upgrade rkvst-python

.github/workflows/python-package.yml, archivist_samples/door_entry/run.py
Problem:
Code used Linux specific tenporary directory.
Solution:
Use tempfile module for OS-agnostic temporary directory.
Test on Windows in Pipeline.
=> Use portable temporary directory

archivist_samples/c2pa/main.py, archivist_samples/c2pa/run.py, archivist_samples/document/main.py, archivist_samples/sbom_document/main.py, archivist_samples/wipp/main.py
[AB#8310](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/8310)
```
$> archivist_samples_document -p SIMPLE_HASH -u https://app.dev-jgough-0.dev.jitsuin.io -t credentials/authtoken 
Initialising connection to RKVST...
Using version v0.25.0 of rkvst-archivist
Fetching use case test assets namespace document
Creating Document Asset ...
Asteroid Mining Inc Invoice does not exist
Invoice Asset Created (Identity=assets/0189d204-5b5a-4d4f-9461-2e4085434e41)
Publishing V2 ...
V2 published, with order number
Publishing V3 ...
V3 published, with discount applied
$> echo $?
0
```
Help still works:
```
$ archivist_samples_document --help
usage: archivist_samples_document [-h] [-v] [-u URL] [-p {KHIPU,SIMPLE_HASH}] -t AUTH_TOKEN_FILE [--namespace NAMESPACE]
Document …
```
=> Ensure run() handles exiting and unreachable code removed

archivist_samples/sbom_document/README.md, archivist_samples/software_bill_of_materials/README.md, requirements.txt
To eliminate use of obsolete Attachments behaviour
[AB#4810](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/4810)
=> Upgrade to rkvst-archivist 0.25.2

.github/workflows/python-package.yml, Taskfile.yml, requirements-dev.txt
Add support for python 3.12
Upgrade pylint to 3.0 and other tools.
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>
=> Support python 3.12

requirements-dev.txt, setup.cfg
twine 4.0 is incompatible with python3.12.
(unable to publish package)
Upgrade twine and fix warnings.
[AB#9329](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9329)
=> Fix twine metadata

archivist_samples/c2pa/c2pa.py, archivist_samples/document/document.py, archivist_samples/door_entry/run.py, archivist_samples/sample_scripts/c2pa/c2pa_verify.py, archivist_samples/sbom_document/software_package.py, archivist_samples/signed_records/main.py, archivist_samples/software_bill_of_materials/software_deployment.py, archivist_samples/software_bill_of_materials/software_package.py, archivist_samples/synsation/synsation_corporation.py, archivist_samples/synsation/synsation_manufacturing.py, archivist_samples/testing/asset.py, archivist_samples/testing/assets.py, archivist_samples/wipp/wipp.py, requirements.txt
test results:
TEST_SELECTOR=all task samples PASSED
TEST_SELECTOR=all task functests PASSED using locally generated wheel
[AB#9779](https://dev.azure.com/jitsuin/0629f48c-3979-4bbc-9026-cb06b3dfd0ae/_workitems/edit/9779)
=> Confirmation is optional

.github/dependabot.yml, .github/workflows/python-package.yml, DEVELOPERS.md, Dockerfile, README.md, Taskfile.yml, archivist_samples/c2pa/README.md, archivist_samples/c2pa/c2pa.py, archivist_samples/document/README.md, archivist_samples/document/document.py, archivist_samples/door_entry/README.md, archivist_samples/estate_info/README.md, archivist_samples/sbom_document/README.md, archivist_samples/signed_records/README.md, archivist_samples/software_bill_of_materials/README.md, archivist_samples/synsation/README.md, archivist_samples/synsation/synsation_industries.py, archivist_samples/synsation/synsation_manufacturing.py, archivist_samples/synsation/synsation_smartcity.py, archivist_samples/testing/assets.py, archivist_samples/wipp/README.md, pyproject.toml, requirements.txt, setup.cfg
Use v0.34.1 of datatatrails-archivist wheel.
Also remove python 3.8 and add python 3.13
Add dependabot.yml
```
Testing results
paul@turing:~/git/datatrails-samples (dev/paul/10628-remove-compliance-policies)$ TEST_SELECTOR=all task samples
task: Task "about" is up to date
task: [samples] ./scripts/api.sh ./scripts/samples.sh
NAMESPACE is 13019
Initialising connection to DataTrails...
User agent is samples/v0.18.0-0-gadd5f77-dirty pysdk/v0.34.0
Using version v0.34.0 of datatrails-archivist
Fetching use case test assets namespace 13019
Creating C2PA Asset ...
Adobe C2PA Image does not exist
C2PA Document Created (Identity=assets/1685d248-10c5-4a25-af01-baaeb9514218)
Creating Info Report ...
Info Report Created
Creating Ingredients ...
Ingredients Created
Creating External Manifest ... …
```
=> Remove compliance policies
